[2022-07-05 09:38:19,726] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sql_branch_dag.branch_sql manual__2022-07-05T09:38:18.851030+00:00 [queued]>
[2022-07-05 09:38:19,745] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sql_branch_dag.branch_sql manual__2022-07-05T09:38:18.851030+00:00 [queued]>
[2022-07-05 09:38:19,745] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 09:38:19,745] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-05 09:38:19,745] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 09:38:19,770] {taskinstance.py:1377} INFO - Executing <Task(BranchSQLOperator): branch_sql> on 2022-07-05 09:38:18.851030+00:00
[2022-07-05 09:38:19,775] {standard_task_runner.py:52} INFO - Started process 806 to run task
[2022-07-05 09:38:19,783] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'sql_branch_dag', 'branch_sql', 'manual__2022-07-05T09:38:18.851030+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/sql_branch_operator.py', '--cfg-path', '/tmp/tmp2wof55yh', '--error-file', '/tmp/tmpwob7bqf5']
[2022-07-05 09:38:19,784] {standard_task_runner.py:80} INFO - Job 130: Subtask branch_sql
[2022-07-05 09:38:20,029] {task_command.py:370} INFO - Running <TaskInstance: sql_branch_dag.branch_sql manual__2022-07-05T09:38:18.851030+00:00 [running]> on host dfb99dfc9d64
[2022-07-05 09:38:20,273] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sql_branch_dag
AIRFLOW_CTX_TASK_ID=branch_sql
AIRFLOW_CTX_EXECUTION_DATE=2022-07-05T09:38:18.851030+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-05T09:38:18.851030+00:00
[2022-07-05 09:38:20,277] {sql.py:513} INFO - Executing: SELECT count(1) FROM dummy (with parameters None) with connection: postgres_con
[2022-07-05 09:38:20,323] {base.py:68} INFO - Using connection ID 'postgres_con' for task execution.
[2022-07-05 09:38:20,789] {base.py:68} INFO - Using connection ID 'postgres_con' for task execution.
[2022-07-05 09:38:20,858] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/sql.py", line 515, in execute
    record = self.get_db_hook().get_first(self.sql, self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 160, in get_first
    cur.execute(sql)
psycopg2.errors.UndefinedTable: relation "dummy" does not exist
LINE 1: SELECT count(1) FROM dummy
                             ^

[2022-07-05 09:38:20,937] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=sql_branch_dag, task_id=branch_sql, execution_date=20220705T093818, start_date=20220705T093819, end_date=20220705T093820
[2022-07-05 09:38:21,045] {standard_task_runner.py:97} ERROR - Failed to execute job 130 for task branch_sql (relation "dummy" does not exist
LINE 1: SELECT count(1) FROM dummy
                             ^
; 806)
[2022-07-05 09:38:21,083] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-05 09:38:21,497] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
