[2022-07-05 05:56:27,036] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xcom_dag.extract_user scheduled__2022-07-04T00:00:00+00:00 [queued]>
[2022-07-05 05:56:27,052] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xcom_dag.extract_user scheduled__2022-07-04T00:00:00+00:00 [queued]>
[2022-07-05 05:56:27,053] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:56:27,054] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-05 05:56:27,054] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 05:56:27,079] {taskinstance.py:1377} INFO - Executing <Task(SimpleHttpOperator): extract_user> on 2022-07-04 00:00:00+00:00
[2022-07-05 05:56:27,088] {standard_task_runner.py:52} INFO - Started process 3485 to run task
[2022-07-05 05:56:27,093] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'xcom_dag', 'extract_user', 'scheduled__2022-07-04T00:00:00+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/xcom_dag.py', '--cfg-path', '/tmp/tmproslqeht', '--error-file', '/tmp/tmpxsjbfe5b']
[2022-07-05 05:56:27,094] {standard_task_runner.py:80} INFO - Job 114: Subtask extract_user
[2022-07-05 05:56:27,170] {task_command.py:370} INFO - Running <TaskInstance: xcom_dag.extract_user scheduled__2022-07-04T00:00:00+00:00 [running]> on host dfb99dfc9d64
[2022-07-05 05:56:27,291] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xcom_dag
AIRFLOW_CTX_TASK_ID=extract_user
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-04T00:00:00+00:00
[2022-07-05 05:56:27,293] {http.py:102} INFO - Calling HTTP method
[2022-07-05 05:56:27,329] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 104, in execute
    response = http.run(self.endpoint, self.data, self.headers, self.extra_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 114, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `user_api` isn't defined
[2022-07-05 05:56:27,334] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=xcom_dag, task_id=extract_user, execution_date=20220704T000000, start_date=20220705T055627, end_date=20220705T055627
[2022-07-05 05:56:27,354] {standard_task_runner.py:97} ERROR - Failed to execute job 114 for task extract_user (The conn_id `user_api` isn't defined; 3485)
[2022-07-05 05:56:27,388] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-05 05:56:27,462] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
