[2022-07-04 16:26:44,925] {processor.py:153} INFO - Started process (PID=4847) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:26:44,925] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:26:44,926] {logging_mixin.py:115} INFO - [2022-07-04 16:26:44,926] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:26:44,954] {logging_mixin.py:115} INFO - [2022-07-04 16:26:44,953] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:26:44,954] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:26:44,973] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.051 seconds
[2022-07-04 16:27:15,258] {processor.py:153} INFO - Started process (PID=4907) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:27:15,259] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:27:15,259] {logging_mixin.py:115} INFO - [2022-07-04 16:27:15,259] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:27:15,271] {logging_mixin.py:115} INFO - [2022-07-04 16:27:15,270] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:27:15,271] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:27:15,290] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.035 seconds
[2022-07-04 16:27:45,752] {processor.py:153} INFO - Started process (PID=4977) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:27:45,753] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:27:45,754] {logging_mixin.py:115} INFO - [2022-07-04 16:27:45,754] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:27:45,765] {logging_mixin.py:115} INFO - [2022-07-04 16:27:45,764] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:27:45,765] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:27:45,785] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.036 seconds
[2022-07-04 16:28:16,142] {processor.py:153} INFO - Started process (PID=5032) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:28:16,142] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:28:16,143] {logging_mixin.py:115} INFO - [2022-07-04 16:28:16,143] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:28:16,154] {logging_mixin.py:115} INFO - [2022-07-04 16:28:16,154] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:28:16,155] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:28:16,175] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.036 seconds
[2022-07-04 16:28:46,892] {processor.py:153} INFO - Started process (PID=5097) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:28:46,893] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:28:46,894] {logging_mixin.py:115} INFO - [2022-07-04 16:28:46,894] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:28:46,905] {logging_mixin.py:115} INFO - [2022-07-04 16:28:46,904] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:28:46,905] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:28:46,926] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.037 seconds
[2022-07-04 16:29:17,114] {processor.py:153} INFO - Started process (PID=5153) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:29:17,115] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:29:17,115] {logging_mixin.py:115} INFO - [2022-07-04 16:29:17,115] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:29:17,126] {logging_mixin.py:115} INFO - [2022-07-04 16:29:17,126] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:29:17,127] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:29:17,146] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.035 seconds
[2022-07-04 16:29:47,480] {processor.py:153} INFO - Started process (PID=5213) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:29:47,489] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:29:47,490] {logging_mixin.py:115} INFO - [2022-07-04 16:29:47,490] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:29:47,534] {logging_mixin.py:115} INFO - [2022-07-04 16:29:47,533] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:29:47,544] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:29:47,601] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.137 seconds
[2022-07-04 16:30:18,585] {processor.py:153} INFO - Started process (PID=5271) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:30:18,585] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:30:18,586] {logging_mixin.py:115} INFO - [2022-07-04 16:30:18,586] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:30:18,598] {logging_mixin.py:115} INFO - [2022-07-04 16:30:18,597] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:30:18,598] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:30:18,617] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.036 seconds
[2022-07-04 16:30:49,005] {processor.py:153} INFO - Started process (PID=5326) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:30:49,006] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:30:49,006] {logging_mixin.py:115} INFO - [2022-07-04 16:30:49,006] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:30:49,018] {logging_mixin.py:115} INFO - [2022-07-04 16:30:49,017] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:30:49,018] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:30:49,040] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.039 seconds
[2022-07-04 16:31:19,293] {processor.py:153} INFO - Started process (PID=5392) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:31:19,294] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:31:19,296] {logging_mixin.py:115} INFO - [2022-07-04 16:31:19,296] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:31:19,308] {logging_mixin.py:115} INFO - [2022-07-04 16:31:19,307] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:31:19,308] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:31:19,328] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.039 seconds
[2022-07-04 16:31:49,771] {processor.py:153} INFO - Started process (PID=5448) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:31:49,773] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:31:49,774] {logging_mixin.py:115} INFO - [2022-07-04 16:31:49,774] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:31:49,787] {logging_mixin.py:115} INFO - [2022-07-04 16:31:49,786] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:31:49,793] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:31:49,816] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.048 seconds
[2022-07-04 16:32:20,292] {processor.py:153} INFO - Started process (PID=5515) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:32:20,292] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:32:20,293] {logging_mixin.py:115} INFO - [2022-07-04 16:32:20,293] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:32:20,304] {logging_mixin.py:115} INFO - [2022-07-04 16:32:20,304] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:32:20,305] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:32:20,325] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.036 seconds
[2022-07-04 16:32:50,885] {processor.py:153} INFO - Started process (PID=5568) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:32:50,885] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:32:50,886] {logging_mixin.py:115} INFO - [2022-07-04 16:32:50,886] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:32:50,904] {logging_mixin.py:115} INFO - [2022-07-04 16:32:50,903] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:32:50,904] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:32:50,926] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.045 seconds
[2022-07-04 16:33:21,371] {processor.py:153} INFO - Started process (PID=5632) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:33:21,373] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:33:21,374] {logging_mixin.py:115} INFO - [2022-07-04 16:33:21,374] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:33:21,388] {logging_mixin.py:115} INFO - [2022-07-04 16:33:21,388] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:33:21,390] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:33:21,427] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.059 seconds
[2022-07-04 16:33:52,206] {processor.py:153} INFO - Started process (PID=5688) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:33:52,208] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:33:52,209] {logging_mixin.py:115} INFO - [2022-07-04 16:33:52,209] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:33:52,221] {logging_mixin.py:115} INFO - [2022-07-04 16:33:52,221] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:33:52,222] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:33:52,245] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.044 seconds
[2022-07-04 16:34:23,062] {processor.py:153} INFO - Started process (PID=5754) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:34:23,064] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:34:23,066] {logging_mixin.py:115} INFO - [2022-07-04 16:34:23,066] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:34:23,091] {logging_mixin.py:115} INFO - [2022-07-04 16:34:23,091] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:34:23,097] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:34:23,142] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.086 seconds
[2022-07-04 16:34:53,897] {processor.py:153} INFO - Started process (PID=5815) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:34:53,898] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:34:53,898] {logging_mixin.py:115} INFO - [2022-07-04 16:34:53,898] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:34:53,910] {logging_mixin.py:115} INFO - [2022-07-04 16:34:53,909] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:34:53,910] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:34:53,936] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.043 seconds
[2022-07-04 16:35:24,236] {processor.py:153} INFO - Started process (PID=5886) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:35:24,238] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:35:24,239] {logging_mixin.py:115} INFO - [2022-07-04 16:35:24,239] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:35:24,258] {logging_mixin.py:115} INFO - [2022-07-04 16:35:24,255] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:35:24,259] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:35:24,285] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.053 seconds
[2022-07-04 16:35:54,491] {processor.py:153} INFO - Started process (PID=5944) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:35:54,492] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:35:54,493] {logging_mixin.py:115} INFO - [2022-07-04 16:35:54,493] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:35:54,507] {logging_mixin.py:115} INFO - [2022-07-04 16:35:54,506] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:35:54,507] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:35:54,528] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.041 seconds
[2022-07-04 16:36:24,986] {processor.py:153} INFO - Started process (PID=6009) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:36:24,987] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:36:24,987] {logging_mixin.py:115} INFO - [2022-07-04 16:36:24,987] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:36:24,999] {logging_mixin.py:115} INFO - [2022-07-04 16:36:24,998] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:36:24,999] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:36:25,020] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.037 seconds
[2022-07-04 16:36:55,582] {processor.py:153} INFO - Started process (PID=6072) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:36:55,584] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:36:55,586] {logging_mixin.py:115} INFO - [2022-07-04 16:36:55,586] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:36:55,599] {logging_mixin.py:115} INFO - [2022-07-04 16:36:55,598] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:36:55,600] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:36:55,625] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.046 seconds
[2022-07-04 16:37:25,970] {processor.py:153} INFO - Started process (PID=6130) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:37:25,970] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:37:25,970] {logging_mixin.py:115} INFO - [2022-07-04 16:37:25,970] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:37:25,982] {logging_mixin.py:115} INFO - [2022-07-04 16:37:25,981] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:37:25,982] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:37:26,002] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.036 seconds
[2022-07-04 16:37:56,369] {processor.py:153} INFO - Started process (PID=6197) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:37:56,371] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:37:56,371] {logging_mixin.py:115} INFO - [2022-07-04 16:37:56,371] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:37:56,383] {logging_mixin.py:115} INFO - [2022-07-04 16:37:56,382] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:37:56,383] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:37:56,405] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.038 seconds
[2022-07-04 16:38:27,105] {processor.py:153} INFO - Started process (PID=6252) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:38:27,106] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:38:27,106] {logging_mixin.py:115} INFO - [2022-07-04 16:38:27,106] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:38:27,128] {logging_mixin.py:115} INFO - [2022-07-04 16:38:27,128] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:38:27,129] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:38:27,170] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.073 seconds
[2022-07-04 16:38:57,445] {processor.py:153} INFO - Started process (PID=6317) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:38:57,450] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:38:57,451] {logging_mixin.py:115} INFO - [2022-07-04 16:38:57,451] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:38:57,464] {logging_mixin.py:115} INFO - [2022-07-04 16:38:57,463] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:38:57,471] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:38:57,495] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.053 seconds
[2022-07-04 16:39:27,666] {processor.py:153} INFO - Started process (PID=6374) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:39:27,668] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:39:27,670] {logging_mixin.py:115} INFO - [2022-07-04 16:39:27,670] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:39:27,692] {logging_mixin.py:115} INFO - [2022-07-04 16:39:27,685] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:39:27,693] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:39:27,725] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.062 seconds
[2022-07-04 16:39:58,315] {processor.py:153} INFO - Started process (PID=6440) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:39:58,317] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:39:58,318] {logging_mixin.py:115} INFO - [2022-07-04 16:39:58,318] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:39:58,332] {logging_mixin.py:115} INFO - [2022-07-04 16:39:58,332] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:39:58,333] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:39:58,354] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.044 seconds
[2022-07-04 16:40:28,902] {processor.py:153} INFO - Started process (PID=6495) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:40:28,902] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:40:28,903] {logging_mixin.py:115} INFO - [2022-07-04 16:40:28,903] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:40:28,915] {logging_mixin.py:115} INFO - [2022-07-04 16:40:28,914] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:40:28,915] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:40:28,935] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.037 seconds
[2022-07-04 16:40:59,091] {processor.py:153} INFO - Started process (PID=6558) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:40:59,093] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:40:59,094] {logging_mixin.py:115} INFO - [2022-07-04 16:40:59,094] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:40:59,106] {logging_mixin.py:115} INFO - [2022-07-04 16:40:59,106] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:40:59,107] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:40:59,128] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.040 seconds
[2022-07-04 16:41:29,495] {processor.py:153} INFO - Started process (PID=6618) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:41:29,495] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:41:29,496] {logging_mixin.py:115} INFO - [2022-07-04 16:41:29,496] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:41:29,507] {logging_mixin.py:115} INFO - [2022-07-04 16:41:29,507] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:41:29,508] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:41:29,527] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.036 seconds
[2022-07-04 16:42:00,046] {processor.py:153} INFO - Started process (PID=6686) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:42:00,048] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:42:00,049] {logging_mixin.py:115} INFO - [2022-07-04 16:42:00,049] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:42:00,061] {logging_mixin.py:115} INFO - [2022-07-04 16:42:00,060] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:42:00,062] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:42:00,097] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.054 seconds
[2022-07-04 16:42:30,748] {processor.py:153} INFO - Started process (PID=6740) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:42:30,749] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:42:30,750] {logging_mixin.py:115} INFO - [2022-07-04 16:42:30,749] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:42:30,761] {logging_mixin.py:115} INFO - [2022-07-04 16:42:30,760] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:42:30,761] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:42:30,786] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.041 seconds
[2022-07-04 16:43:01,452] {processor.py:153} INFO - Started process (PID=6796) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:43:01,454] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:43:01,456] {logging_mixin.py:115} INFO - [2022-07-04 16:43:01,456] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:43:01,469] {logging_mixin.py:115} INFO - [2022-07-04 16:43:01,468] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:43:01,469] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:43:01,489] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.043 seconds
[2022-07-04 16:43:32,018] {processor.py:153} INFO - Started process (PID=6859) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:43:32,019] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:43:32,019] {logging_mixin.py:115} INFO - [2022-07-04 16:43:32,019] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:43:32,031] {logging_mixin.py:115} INFO - [2022-07-04 16:43:32,030] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:43:32,031] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:43:32,052] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.037 seconds
[2022-07-04 16:44:02,413] {processor.py:153} INFO - Started process (PID=6915) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:44:02,425] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:44:02,426] {logging_mixin.py:115} INFO - [2022-07-04 16:44:02,426] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:44:02,450] {logging_mixin.py:115} INFO - [2022-07-04 16:44:02,438] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:44:02,451] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:44:02,497] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.087 seconds
[2022-07-04 16:44:32,677] {processor.py:153} INFO - Started process (PID=6978) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:44:32,677] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:44:32,678] {logging_mixin.py:115} INFO - [2022-07-04 16:44:32,678] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:44:32,689] {logging_mixin.py:115} INFO - [2022-07-04 16:44:32,688] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:44:32,689] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:44:32,712] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.039 seconds
[2022-07-04 16:45:02,854] {processor.py:153} INFO - Started process (PID=7037) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:45:02,858] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:45:02,859] {logging_mixin.py:115} INFO - [2022-07-04 16:45:02,859] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:45:02,901] {logging_mixin.py:115} INFO - [2022-07-04 16:45:02,900] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:45:02,904] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:45:02,946] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.102 seconds
[2022-07-04 16:45:32,997] {processor.py:153} INFO - Started process (PID=7101) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:45:32,999] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:45:33,000] {logging_mixin.py:115} INFO - [2022-07-04 16:45:33,000] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:45:33,031] {logging_mixin.py:115} INFO - [2022-07-04 16:45:33,026] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:45:33,032] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:45:33,067] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.073 seconds
[2022-07-04 16:46:03,379] {processor.py:153} INFO - Started process (PID=7160) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:46:03,380] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:46:03,381] {logging_mixin.py:115} INFO - [2022-07-04 16:46:03,381] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:46:03,393] {logging_mixin.py:115} INFO - [2022-07-04 16:46:03,392] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:46:03,393] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:46:03,419] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.044 seconds
[2022-07-04 16:46:33,758] {processor.py:153} INFO - Started process (PID=7216) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:46:33,759] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:46:33,759] {logging_mixin.py:115} INFO - [2022-07-04 16:46:33,759] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:46:33,788] {logging_mixin.py:115} INFO - [2022-07-04 16:46:33,788] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:46:33,789] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:46:33,847] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.092 seconds
[2022-07-04 16:47:04,473] {processor.py:153} INFO - Started process (PID=7273) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:47:04,479] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:47:04,481] {logging_mixin.py:115} INFO - [2022-07-04 16:47:04,481] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:47:04,505] {logging_mixin.py:115} INFO - [2022-07-04 16:47:04,503] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:47:04,506] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:47:04,543] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.077 seconds
[2022-07-04 16:47:34,935] {processor.py:153} INFO - Started process (PID=7327) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:47:34,935] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:47:34,936] {logging_mixin.py:115} INFO - [2022-07-04 16:47:34,935] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:47:34,971] {logging_mixin.py:115} INFO - [2022-07-04 16:47:34,970] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:47:34,971] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:47:35,031] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.108 seconds
[2022-07-04 16:48:05,062] {processor.py:153} INFO - Started process (PID=7389) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:48:05,080] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:48:05,085] {logging_mixin.py:115} INFO - [2022-07-04 16:48:05,085] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:48:05,107] {logging_mixin.py:115} INFO - [2022-07-04 16:48:05,107] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:48:05,115] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:48:05,149] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.090 seconds
[2022-07-04 16:48:35,578] {processor.py:153} INFO - Started process (PID=7445) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:48:35,589] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:48:35,590] {logging_mixin.py:115} INFO - [2022-07-04 16:48:35,590] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:48:35,618] {logging_mixin.py:115} INFO - [2022-07-04 16:48:35,617] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:48:35,623] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:48:35,660] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.084 seconds
[2022-07-04 16:49:05,682] {processor.py:153} INFO - Started process (PID=7511) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:49:05,683] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:49:05,683] {logging_mixin.py:115} INFO - [2022-07-04 16:49:05,683] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:49:05,695] {logging_mixin.py:115} INFO - [2022-07-04 16:49:05,694] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:49:05,695] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:49:05,717] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.038 seconds
[2022-07-04 16:49:36,257] {processor.py:153} INFO - Started process (PID=7564) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:49:36,262] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:49:36,263] {logging_mixin.py:115} INFO - [2022-07-04 16:49:36,263] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:49:36,303] {logging_mixin.py:115} INFO - [2022-07-04 16:49:36,299] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:49:36,305] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:49:36,351] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.098 seconds
[2022-07-04 16:50:06,583] {processor.py:153} INFO - Started process (PID=7630) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:50:06,583] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:50:06,583] {logging_mixin.py:115} INFO - [2022-07-04 16:50:06,583] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:50:06,595] {logging_mixin.py:115} INFO - [2022-07-04 16:50:06,594] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:50:06,595] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:50:06,614] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.035 seconds
[2022-07-04 16:50:36,953] {processor.py:153} INFO - Started process (PID=7686) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:50:36,954] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:50:36,955] {logging_mixin.py:115} INFO - [2022-07-04 16:50:36,955] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:50:36,966] {logging_mixin.py:115} INFO - [2022-07-04 16:50:36,966] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:50:36,967] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:50:36,988] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.038 seconds
[2022-07-04 16:51:07,178] {processor.py:153} INFO - Started process (PID=7755) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:51:07,180] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:51:07,181] {logging_mixin.py:115} INFO - [2022-07-04 16:51:07,181] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:51:07,193] {logging_mixin.py:115} INFO - [2022-07-04 16:51:07,193] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:51:07,195] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:51:07,216] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.041 seconds
[2022-07-04 16:51:37,474] {processor.py:153} INFO - Started process (PID=7810) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:51:37,476] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:51:37,477] {logging_mixin.py:115} INFO - [2022-07-04 16:51:37,476] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:51:37,488] {logging_mixin.py:115} INFO - [2022-07-04 16:51:37,487] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:51:37,488] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:51:37,512] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.041 seconds
[2022-07-04 16:52:07,587] {processor.py:153} INFO - Started process (PID=7875) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:52:07,589] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:52:07,592] {logging_mixin.py:115} INFO - [2022-07-04 16:52:07,592] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:52:07,604] {logging_mixin.py:115} INFO - [2022-07-04 16:52:07,604] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:52:07,605] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:52:07,631] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.057 seconds
[2022-07-04 16:52:37,786] {processor.py:153} INFO - Started process (PID=7928) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:52:37,788] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-04 16:52:37,790] {logging_mixin.py:115} INFO - [2022-07-04 16:52:37,790] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:52:37,817] {logging_mixin.py:115} INFO - [2022-07-04 16:52:37,817] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-04 16:52:37,818] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-04 16:52:37,839] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.056 seconds
